name: agora
description: Agora project.

publish_to: 'none'

version: 3.2.1+85

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.3
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.4.2
  dio_http2_adapter: ^2.4.0
  basic_utils: ^5.7.0
  intl: ^0.19.0
  get_it: ^8.0.0
  flutter_html: ^3.0.0-beta.2 # not support for web
  url_launcher: ^6.3.0
  logger: ^2.0.2+1
  device_info_plus: ^10.1.2
  permission_handler: ^11.1.0 # not support for web
  video_player: ^2.7.1
  chewie: ^1.5.0
  share_plus: ^10.0.3
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  flutter_local_notifications: ^17.2.2 # not support for web
  flutter_secure_storage: ^9.0.0
  matomo_tracker: ^5.1.0
  percent_indicator: ^4.2.3
  webview_flutter: ^4.2.4 # not support for web
  flutter_widget_from_html: ^0.15.2 # only support web
  responsive_framework: ^1.1.0
  package_info_plus: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  sentry_flutter: ^8.9.0
  shimmer: ^3.0.0
  diacritic: ^0.1.4
  lottie: ^3.1.3
  intersperse: ^2.0.0
  collection: ^1.18.0
  dotted_border: ^2.1.0
  app_links: ^6.3.1
  error_stack: ^1.9.0
  optional: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.4
  http_mock_adapter: ^0.6.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.6
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/launcher_icons/
    - assets/animations/
    - assets/certificates/
  fonts:
    - family: Marianne
      fonts:
        - asset: fonts/Marianne/normal/Marianne-ExtraBold.otf
          weight: 900
        - asset: fonts/Marianne/normal/Marianne-Bold.otf
          weight: 800
        - asset: fonts/Marianne/normal/Marianne-Medium.otf
          weight: 700
        - asset: fonts/Marianne/italic/Marianne-MediumItalic.otf
          weight: 700
          style: italic
        - asset: fonts/Marianne/normal/Marianne-Regular.otf
          weight: 500
        - asset: fonts/Marianne/italic/Marianne-RegularItalic.otf
          weight: 500
          style: italic
        - asset: fonts/Marianne/normal/Marianne-Light.otf
          weight: 400
        - asset: fonts/Marianne/italic/Marianne-LightItalic.otf
          weight: 400
          style: italic
        - asset: fonts/Marianne/normal/Marianne-Thin.otf
          weight: 300

